# Kommentti: Tämä on GitHub Actions -tiedosto, joka käynnistää Docker-kontin rakentamisen ja julkaisun Azure Container Registryyn sekä julkaisun Azure App Serviceen. Tiedosto on kopioitu mallista
name: Build and Deploy to Azure

on:
  push:
    branches:
      - main  # replace with your branch name

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v2

    - name: 'Login to ACR'
      uses: docker/login-action@v1
      with:
        registry: 'flasksovellusmalli.azurecr.io' # Replace with your ACR name
        username: '${{ secrets.ACR_USERNAME }}' # Replace with your ACR username
        password: '${{ secrets.ACR_PASSWORD }}' # Replace with your ACR password

    - name: 'Build and push Docker image'
      uses: docker/build-push-action@v2
      with:
        context: '.'
        push: true
        tags: 'flasksovellusmalli.azurecr.io/flask-sovellusmalli-i:latest' # Replace with your ACR name
        log_level: debug

    - name: 'Login to Azure'
      uses: azure/login@v1
      with:
        creds: '${{ secrets.AZURE_CREDENTIALS }}' # Replace with your Azure credentials

    - name: 'Deploy to Azure WebApp'
      uses: azure/webapps-deploy@v2
      with: 
        app-name: 'flask-sovellusmalli-i' # Replace with your app name
        slot-name: 'production' # If you have a deployment slot, replace with your slot name
        publish-profile: '${{ secrets.AzureAppService_PublishProfile_SecretName }}' # Replace with your secret name
        images: 'flasksovellusmalli.azurecr.io/flask-sovellusmalli-i:latest' # Replace with your ACR name and Docker image